plugins:
  - jekyll-seo-tag

title: About Puttin

# if we stick with GitHub Pages' Jekyll, then only GFM or CommonMarkGhPages or Kramdown is acceptable
# 'GFM' doesn't allow changes about commonmark which 'CommonMarkGhPages' allows
# e.g., removing 'tagfilter' extension
# see also `restrict_and_config_markdown_processor` in gem 'github-pages'
# maybe the easier way is generating static site directly then publishing to branch 'gh-pages' 
# instead of using Github's Jekyll version
markdown: CommonMarkGhPages
commonmark:
  extensions: ["strikethrough"]
